# flake.module.nix — project-specific flake-parts customizations.
#
# seihou does NOT manage this file: it is never regenerated or overwritten by
# `seihou run` or module migrations, so it is the conflict-free home for every
# customization that must survive nix-haskell-flake template upgrades. See
# flake.module.nix.example (generated by the module) for the full option list.
#
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ REQUIRED: this file MUST be git-tracked (`git add flake.module.nix`).      │
# │ Nix flakes evaluate only files tracked by git, so flake.nix's             │
# │ `builtins.pathExists ./flake.module.nix` import guard sees an untracked   │
# │ file as ABSENT and silently ignores everything below — no error, the      │
# │ customization just vanishes from the dev shell. After `git add`, prove it │
# │ took effect with `nix print-dev-env | grep <tool>`.                        │
# └──────────────────────────────────────────────────────────────────────────┘
{ ... }:
{
  perSystem = { pkgs, config, ... }: {
    # Extra dev-shell tools (conflict-free; reads the option declared in the
    # seihou-managed ./nix/haskell.nix). These previously lived inline in
    # nix/haskell.nix's extraNativeBuildInputs and were relocated here so they
    # survive template upgrades.
    haskellProject.extraDevPackages = [
      # librdkafka: the C library hw-kafka-client / kafka-effectful link against.
      pkgs.rdkafka
      # just: task runner for this project's recipes.
      pkgs.just
      # process-compose: runs the local dev process stack (see process-compose.yaml).
      pkgs.process-compose
    ];
  };
}
